using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Interactions;

public class InputManager : MonoBehaviour
{
    [SerializeField] private PlayerInput PlayerInput;
    
    public Vector2 Move { get; private set; }
    public Vector2 Look { get; private set; }

    private InputActionMap _currentMap;
    private InputAction _moveAction;
    private InputAction _lookAction;


    private void Awake() {
        HideCursor();
        _currentMap = PlayerInput.currentActionMap;
        _moveAction = _currentMap.FindAction("Move");
        _lookAction = _currentMap.FindAction("Look");


        _moveAction.performed += onMove;
        _lookAction.performed += onLook;


        _moveAction.canceled += onMove;
        _lookAction.canceled += onLook;


    }

    private void HideCursor () {
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
    }


    private void onMove(InputAction.CallbackContext context) {
        Move = context.ReadValue<Vector2>();
    }

    private void onLook(InputAction.CallbackContext context) {
        Look = context.ReadValue<Vector2>();
    }


    private void OnEnable() {
        _currentMap.Enable();
    }


    private void OnDisable() {
        _currentMap.Disable();
    }

}
